name: Profile Views Counter

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:       # manual trigger

jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch total unique views
        id: traffic
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIST_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Fetch traffic views (last 14 days)
            const response = await github.rest.repos.getViews({
              owner,
              repo,
              per: "day"
            });

            // Sum unique visitors
            const totalUnique = response.data.views.reduce((sum, day) => sum + day.uniques, 0);

            console.log(`Total unique visitors: ${totalUnique}`);
            return totalUnique;

      - name: Update Gist badge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIST_TOKEN }}
          script: |
            const gistId = "1f6d9d8aae0ce40d7e91141e52af082b"; // Replace with your Gist ID
            const totalViews = ${{ steps.traffic.outputs.result }};
            const content = JSON.stringify({ value: totalViews, label: "Profile Views" });

            await github.gists.update({
              gist_id: gistId,
              files: { "views.json": { content } },
              description: "Updated GitHub profile view count"
            });
